// NOTICE: This file was automatically generated by UCPP; do not edit this file manualy.
// UCPP Version 1.6; http://wiki.beyondunreal.com/wiki/UCPP
// #pragma ucpp include ../../UsUnit/macros.inc
class TEST_Cookie extends TEST_BaseRequest;

function run()
{
    idx++;
    switch (idx)
    {
        case 0:
            sock.OnComplete = TestSetupComplete;
            sock.get(getUrl(0));
            break;
        case 1:
            sock.OnComplete = DownloadComplete;
            sock.get(getUrl(0));
            break;
        case 2:
            sock.OnComplete = TestSetupComplete;
            sock.get(getUrl(2));
            break;
        case 3:
            sock.OnComplete = DownloadComplete;
            sock.get(getUrl(2));
            break;
        default:
            Done();
    }
}

function TestSetupComplete(HttpSock Sender)
{
    SetTimer(0.001, false);
}

defaultproperties
{
    TestName="LibHTTP Cookie Test"
    TestDescription="Set and get cookie data"

    URLS[0]="http://%TestLocation%cookie.php?cookiename=testcookie1&token=%token%"
    URLdesc[1]="Set and get the cookie"
    URLS[2]="http://%TestLocation%cookie.php?cookiename=testcookie2&token=%token%&lifetime=3600"
    URLdesc[3]="A cookie with a lifetime"
}