// NOTICE: This file was automatically generated by UCPP; do not edit this file manualy.
// UCPP Version 1.6; http://wiki.beyondunreal.com/wiki/UCPP
// #pragma ucpp include ../../UsUnit/macros.inc
class TEST_Requests extends TEST_BaseRequest;

function run()
{
    idx++;
    if (idx < URLS.length)
    {
        sock.get(getUrl(idx));
    }
    else Done();
}

defaultproperties
{
    TestName="LibHTTP Request Tests"
    TestDescription="Tests various forms of requests (GET only)"

    URLS[0]="http://%TestLocation%PlainText.txt"
    URLdesc[0]="Plain text request"
    URLS[1]="http://%TestLocation%XHTML.html"
    URLdesc[1]="XHTML request"
    URLS[2]="http://TestUser:TestPass@%TestLocation%auth-basic/"
    URLdesc[2]="Basic authentication"
    URLS[3]="http://TestUser:TestPass@%TestLocation%auth-digest/"
    URLdesc[3]="Digest authentication"
    URLS[4]="http://%TestLocation%get.php?token=%Token%"
    URLdesc[4]="Request variables"
    URLS[5]="http://TestUser:TestPass@%TestLocation%redirect.php"
    URLdesc[5]="Redirect"
    URLS[6]="http://TestUser:TestPass@%TestLocation%auth-basic"
    URLdesc[6]="Redirect and authentication"
}